"""add column organization_id

Revision ID: 5649d8643072
Revises: 668af6a66a46
Create Date: 2026-01-11 16:02:06.627891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5649d8643072'
down_revision: Union[str, Sequence[str], None] = '668af6a66a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('services_user_id_fkey'), 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'organizations', ['organization_id'], ['id'])
    op.drop_column('services', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key(op.f('services_user_id_fkey'), 'services', 'users', ['user_id'], ['id'])
    op.drop_column('services', 'organization_id')
    # ### end Alembic commands ###
